name: Java CI

on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}


    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build + Testes
        run: mvn clean verify -B

 #     - name: Checkstyle
 #       run: mvn checkstyle:check

      - name: PMD
        run: mvn pmd:check

      - name: SpotBugs
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs

#      - name: 🔐 Dependency Check (OWASP)
#        run: mvn org.owasp:dependency-check-maven:check